# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratum" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "65d470c0f802e287a219fda96a306ed25415c219cb484f5641dcda8d69dd0e8d"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bcbc095dfaa964d59fd0166281b46ec51bcaa67a462eb576adbe14af7e2fceed"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbc5bcf76bb46546bcf931f61900d1342f7d0f71c085040b14bd6c7ab0f5952a"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ba59fe46a8d648f2549488897cb228ae110bb9a57295630b51b7e348b075ff01"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Linux_arm64.tar.gz"
    end
  end

  name "stratum"
  desc "Code-to-cloud security scanner with ARS risk scoring"
  homepage "https://github.com/utkarshrai2811/stratum-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stratum"]
    end
  end

  # No zap stanza required

end
