# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratum" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0bf163337e1dc78f3e25c9c55ef251bfad1e0398059bbef6eb2ca798f2da8db5"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bc364a7db82ab372a6cd2a7183710809884098d2835e81184e0daf001c4074d7"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09f0c9c2a67d46444b0e2a0aeff42d036bf45803a94499769e6339a72a31a22f"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "90179952eddedf735169dcefba7c343db68bdd02936b1dfdf1bc7cc680a97415"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Linux_arm64.tar.gz"
    end
  end

  name "stratum"
  desc "Code-to-cloud security scanner with ARS risk scoring"
  homepage "https://github.com/utkarshrai2811/stratum-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stratum"]
    end
  end

  # No zap stanza required

end
