# This file was generated by GoReleaser. DO NOT EDIT.
cask "stratum" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "7a077296653fd5fbb7f4ce0d086b830ad6ae4eccf016bc3a611c27eced6cb607"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "03190712c5d07c370a4b59cf9cc45c7fa274100a4294206f689efb82ae96587a"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b1a45af1432ff24dcacbb08eb0492021c6cfea2a6519e8e1828f3275e95d46e5"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ef20dd7964c656b1ad3235c699b590b75dccc64fca0ff610e61d31512562300"
      url "https://github.com/utkarshrai2811/stratum-releases/releases/download/v#{version}/stratum_Linux_arm64.tar.gz"
    end
  end

  name "stratum"
  desc "Code-to-cloud security scanner with ARS risk scoring"
  homepage "https://github.com/utkarshrai2811/stratum-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stratum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stratum"]
    end
  end

  # No zap stanza required

end
